language: go

matrix:
  include:
  - go: "1.11.x"
    script: 
    - go test -v -mod=vendor ./...
    - go build
  - go: "1.13"
    script: 
    - go test -v -mod=vendor ./...
    - go build
    
env:
  - GO111MODULE=on
  
install: true
